/**
 * scripts/seed_full_app.js  —  "God Mode" MASSIVE full-application seeder
 *
 * Self-contained generation engine. Owns and rebuilds EVERYTHING:
 *   • memorial_sites      ~120  (each with a cover image)
 *   • routes              ~24   (each with cover + map image)
 *   • route_waypoints     ~120  (FK → routes, ordered)
 *   • site_galleries      ~480  (3–5 per site)
 *   • profiles            ~55   (real Auth users, avatars, bios)
 *   • community_activities ~450 (candle/route/visit/story)
 *   • community_posts     ~170  ┐ require schema_full_app.sql; the seeder
 *   • community_comments  ~340  │ auto-detects + skips gracefully if the
 *   • saved_routes        ~280  │ optional tables/columns are absent.
 *   • saved_memorials     ~420  ┘
 *
 * Content is generated by composing authentic building blocks (real regions,
 * wars, IDF units, battle archetypes) into diverse, respectful Hebrew prose —
 * thousands of permutations so no two sites read alike.
 *
 * Batched inserts (50/req). FK-safe ordering. Idempotent (truncates first).
 *
 * Run: node --use-system-ca scripts/seed_full_app.js
 */

import { readFileSync }  from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { randomUUID }    from 'crypto'
import { createClient }  from '@supabase/supabase-js'

// ── .env ──────────────────────────────────────────────────────────────────────
const __dirname = dirname(fileURLToPath(import.meta.url))
try {
  const raw = readFileSync(join(__dirname, '../.env'), 'utf8')
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim(); if (!t || t.startsWith('#')) continue
    const eq = t.indexOf('='); if (eq < 0) continue
    let k = t.slice(0, eq).trim(), v = t.slice(eq + 1).trim()
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1)
    if (k && process.env[k] === undefined) process.env[k] = v
  }
} catch {}

const SUPABASE_URL = process.env.VITE_SUPABASE_URL
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY

// ── Targets ───────────────────────────────────────────────────────────────────
const N_SITES     = 120
const N_ROUTES    = 24
const N_PROFILES  = 55
const N_ACTIVITY  = 450
const N_POSTS     = 170
const N_SAVED_RT  = 280
const N_SAVED_MEM = 420
const BATCH       = 50

// ── Deterministic-ish RNG (stable output across runs) ────────────────────────
let _seed = 20260517
const rnd  = () => (_seed = (_seed * 1664525 + 1013904223) % 4294967296) / 4294967296
const ri   = (a, b) => a + Math.floor(rnd() * (b - a + 1))
const pick = arr => arr[Math.floor(rnd() * arr.length)]
const some = (arr, n) => { const c = [...arr]; const o = []; while (o.length < n && c.length) o.push(c.splice(Math.floor(rnd()*c.length),1)[0]); return o }

// ── Reliable image helpers (picsum + pravatar never 404) ─────────────────────
const img    = (slug, w, h) => `https://picsum.photos/seed/${encodeURIComponent(slug)}/${w}/${h}`
const avatar = key => `https://i.pravatar.cc/300?u=${encodeURIComponent(key)}`

// ══════════════════════════════════════════════════════════════════════════════
//  CONTENT BUILDING BLOCKS  (authentic)
// ══════════════════════════════════════════════════════════════════════════════

const REGIONS = [
  ['רמת הגולן',               32.85, 33.30, 35.62, 35.90, 'רכס בזלת', 'בינוני'],
  ['הגליל העליון',            32.95, 33.28, 35.30, 35.62, 'פסגת הר מיוערת', 'בינוני'],
  ['הגליל התחתון',            32.65, 32.92, 35.20, 35.55, 'גבעה ירוקה', 'קל'],
  ['עמק החולה',               33.05, 33.25, 35.55, 35.66, 'מישור העמק', 'קל'],
  ['עמק יזרעאל',              32.55, 32.72, 35.10, 35.40, 'שדה פתוח', 'קל'],
  ['הכרמל וחיפה',             32.55, 32.85, 34.93, 35.10, 'מדרון הכרמל', 'בינוני'],
  ['בקעת הירדן והכנרת',       32.65, 32.90, 35.50, 35.62, 'חוף האגם', 'קל'],
  ['השרון',                   32.10, 32.50, 34.80, 35.00, 'חורש אלונים', 'קל'],
  ['גוש דן והמרכז',           31.95, 32.15, 34.75, 34.95, 'פארק עירוני', 'קל'],
  ['פרוזדור ירושלים',         31.75, 31.86, 34.95, 35.15, 'מעלה הררי', 'בינוני'],
  ['הרי ירושלים ויהודה',      31.65, 31.82, 35.10, 35.30, 'טרשי יהודה', 'קשה'],
  ['השפלה',                   31.55, 31.85, 34.70, 34.95, 'גבעות השפלה', 'קל'],
  ['עוטף עזה והנגב המערבי',   31.20, 31.60, 34.35, 34.66, 'שדות הבשור', 'קל'],
  ['באר שבע והנגב הצפוני',    30.95, 31.35, 34.65, 35.05, 'מרחב מדברי', 'בינוני'],
  ['הנגב הדרומי והערבה',      29.95, 30.95, 34.40, 35.20, 'מכתש ומדבר', 'קשה'],
  ['הרי אילת',                29.55, 29.90, 34.85, 35.05, 'הר גרניט אדום', 'קשה'],
]

// [hebrew name, category, ISO start, ISO end]
const WARS = [
  ['מלחמת העצמאות',          'מלחמת העצמאות',        '1947-11-30', '1949-07-20'],
  ['מבצע קדש',               'מבצע קדש',              '1956-10-29', '1956-11-05'],
  ['מלחמת ששת הימים',        'מלחמת ששת הימים',       '1967-06-05', '1967-06-10'],
  ['מלחמת ההתשה',            'מלחמת ההתשה',           '1967-07-01', '1970-08-07'],
  ['מלחמת יום הכיפורים',     'מלחמת יום הכיפורים',    '1973-10-06', '1973-10-24'],
  ['מלחמת שלום הגליל',       'מלחמת שלום הגליל',      '1982-06-06', '1982-09-29'],
  ['רצועת הביטחון בלבנון',   'נפגעי פעולות איבה',     '1985-06-01', '2000-05-24'],
  ['מלחמת לבנון השנייה',     'מלחמת לבנון השנייה',    '2006-07-12', '2006-08-14'],
  ['מבצע עופרת יצוקה',       'נפגעי פעולות איבה',     '2008-12-27', '2009-01-18'],
  ['מבצע צוק איתן',          'נפגעי פעולות איבה',     '2014-07-08', '2014-08-26'],
  ['מלחמת חרבות ברזל',       'חרבות ברזל',            '2023-10-07', '2024-12-31'],
  ['פעולות התגמול',          'נפגעי פעולות איבה',     '1953-01-01', '1956-10-01'],
  ['ההגנה על יישובי הספר',  'נפגעי פעולות איבה',     '1936-04-19', '1939-09-01'],
]

const UNITS = [
  'חטיבת גולני', 'גדוד 51 גולני', 'גדוד 13 גולני', 'סיירת גולני',
  'חטיבת הצנחנים', 'גדוד 101 צנחנים', 'גדוד 890 צנחנים', 'גדוד 202 צנחנים',
  'חטיבת גבעתי', 'גדוד שקד', 'גדוד צבר', 'חטיבת הנח"ל', 'גדוד 932 נח"ל',
  'חטיבת כפיר', 'גדוד נצח יהודה', 'גדוד דוכיפת', 'גדוד חרוב',
  'חטיבה 7 שריון', 'גדוד 77 "עוז"', 'חטיבה 188 "ברק"', 'חטיבה 401',
  'חטיבה 460', 'סיירת מטכ"ל', 'שייטת 13', 'יחידת שלדג', 'יחידת אגוז',
  'יחידת מגלן', 'יחידת דובדבן', 'חיל ההנדסה הקרבית', 'יחידה 601',
  'חיל התותחנים', 'מסוף יס"מ', 'מג"ב הצפון', 'חיל האוויר — טייסת קרב',
  'חטיבת אלכסנדרוני', 'חטיבת כרמלי', 'חטיבת יפתח', 'חטיבת הראל',
  'חטיבת עציוני', 'הפלמ"ח', 'ארגון "ההגנה"', 'חטיבת הבקעה',
]

const SITE_TYPES = [
  ['אנדרטת',     'אנדרטה'], ['יד ל',     'אנדרטה'], ['מצפה',       'תצפית'],
  ['גן הנצחה',   'אנדרטה'], ['חניון',    'חניון'],  ['אתר הנצחה',  'אנדרטה'],
  ['גבעת',       'אנדרטה'], ['תצפית',    'תצפית'],  ['בית עדות',   'אנדרטה'],
  ['נקודת ציון', 'אנדרטה'],
]

const SITE_NOUNS = [
  'הגבורה', 'הלוחמים', 'הנופלים', 'הזיכרון', 'הגיבורים', 'הנצח', 'הדמעות',
  'המגינים', 'הראשונים', 'הצנחנים', 'השריון', 'הסיירים', 'הפלוגה',
  'הנערים', 'המתנדבים', 'בני המקום', 'הדור', 'הברית', 'האחים', 'התקומה',
]

const ARCHETYPES = [
  'בלמה בגופה מתקפת פתע',
  'פרצה את קווי האויב בקרב לילה',
  'הגנה על היישוב עד כלות התחמושת',
  'חילצה פצועים תחת אש כבדה',
  'כבשה מוצב מבוצר בקרב פנים-אל-פנים',
  'שברה מצור ממושך וקטלני',
  'ניהלה קרב עיכוב שאיפשר את התארגנות העורף',
  'סיכלה חדירת מחבלים לעבר היישובים',
  'יצאה למבצע חילוץ נועז מעבר לקווים',
  'עמדה לבדה מול כוח גדול פי כמה',
  'אבטחה את ציר האספקה החיוני',
  'הדפה גל הסתערות אחר גל',
]

const HEROISM = [
  'הלוחמים סירבו לסגת גם כשאזלה התחמושת, והחזיקו את הקו בגופם.',
  'מפקד הכוח, שנפצע אנוש, המשיך לפקד עד שהובטח שכל אנשיו חולצו.',
  'שניים מן הלוחמים חזרו שוב ושוב אל אש האויב כדי לחלץ את חבריהם.',
  'בחושך מוחלט, ובשתיקה גמורה, נעו הלוחמים אל היעד וכבשוהו בהפתעה.',
  'גם מוקפים מכל עבר, לא נכנע איש — והקרב הוכרע ברגע האחרון.',
  'נער בן תשע-עשרה נטל את הפיקוד לאחר שמפקדיו נפלו, והוביל להכרעה.',
  'הקרב נמשך שעות ארוכות, יד ביד, עד שהושג הניצחון במחיר כבד.',
  'תחת מטר אש, פילסו הלוחמים נתיב והצילו עשרות אזרחים לכודים.',
]

const LEGACY = [
  'האתר משמש כיום כנקודת עלייה לרגל למשפחות השכולות ולסיורי מורשת קרב.',
  'מדי שנה, בערב יום הזיכרון, נאספים כאן בני הדור ומדליקים אבוקות.',
  'משלחות נוער מכל הארץ עוצרות כאן ללמוד על המחיר ועל המשמעות.',
  'הכיתוב החרוט באבן מזכיר לכל עובר אורח את שם כל אחד מן הנופלים.',
  'מן התצפית נשקף מרחב הקרב כולו, וניתן להבין את עוצמת ההכרעה.',
  'האנדרטה, שעוצבה בידי אמן שכול, הפכה לסמל מוכר בתודעה הלאומית.',
  'הסיפור מסופר כאן בלוחות עדות, מפי הלוחמים ששרדו ובני המשפחות.',
]

const RANKS  = ['טור\'', 'רב"ט', 'סמל', 'סמ"ר', 'רס"ל', 'סג"ם', 'סגן', 'סרן', 'רס"ן', 'סא"ל', 'אל"ם']
const FNAMES = ['רון','יואב','איתי','דניאל','אורי','עומר','נעם','איתן','גיא','אסף','יונתן','אלעד','עידו','ניר','טל','עמית','רועי','שגיא','אבישי','נדב','יותם','הראל','ליאור','עוז','אמיר','בועז','אריאל','מתן','שי','עידן','דור','יהונתן','אלון','גלעד','תומר','אופיר','נריה','עמיחי','אבנר','יואל']
const LNAMES = ['כהן','לוי','מזרחי','פרץ','ביטון','אברהם','פרידמן','אזולאי','דהן','גבאי','אוחיון','שפירא','רוזן','ברק','גולן','הראל','נבון','אדרי','חדד','אשכנזי','בן-דוד','אמסלם','קליין','שרון','דרור','בר-און','נחמיאס','אלבז','סויסה','מועלם','טל','רביב','שני','אורן','כרמי','יפרח','בן-חמו','מלכה','אסולין','גרין']
const MOTTOS = ['אחרי!','הטוב לחיים','בְּמוֹתָם צִוּוּ לָנוּ אֶת הַחַיִּים','נצח ישראל לא ישקר','עם הנצח לא מפחד','עד כאן','שלהבת לא תכבה','כי בנו בטחו','יחד עד הסוף']

function fullName() { return `${pick(FNAMES)} ${pick(LNAMES)}` }

function buildDescription(region, war, unit) {
  const arche = pick(ARCHETYPES)
  const s1 = `ב${region[0]}, על ${region[5]}, ניצב אתר הנצחה ל${pick(SITE_NOUNS)}.`
  const s2 = `במהלך ${war[0]}, ${arche} כאן ${unit}.`
  const s3 = pick(HEROISM)
  const s4 = pick(LEGACY)
  return `${s1} ${s2} ${s3} ${s4}`
}

function buildDedication(unit, war) {
  const n = ri(3, 84)
  const variant = ri(0, 3)
  if (variant === 0) return `על שם ${pick(RANKS)} ${fullName()} ז"ל, ${unit}, שנפל/ה ב${war[0]}`
  if (variant === 1) return `לזכר ${n} לוחמי ${unit} שנפלו ב${war[0]}`
  if (variant === 2) return `מוקדש ל${unit} — "${pick(MOTTOS)}"`
  return `לזכר בני המקום ולוחמי ${unit} שנפלו בהגנת הספר`
}

function randDateISO([, , start, end]) {
  const a = new Date(start).getTime(), b = new Date(end).getTime()
  return new Date(a + rnd() * (b - a)).toISOString().slice(0, 10)
}
function backdatedISO(maxDays) {
  return new Date(Date.now() - rnd() * maxDays * 86_400_000).toISOString()
}
function haversineKm(a, b, c, d) {
  const R = 6371, t = x => x * Math.PI / 180
  const dLa = t(c - a), dLo = t(d - b)
  const h = Math.sin(dLa/2)**2 + Math.cos(t(a))*Math.cos(t(c))*Math.sin(dLo/2)**2
  return R * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h))
}
function durationHe(km, stops) {
  const min = km < 12 ? Math.round(km/3.5*60)+stops*20 : Math.round(km/45*60)+stops*35
  const h = Math.floor(min/60), m = min%60
  return h === 0 ? `${m} דקות` : m === 0 ? `${h} שעות` : `${h} שעות ו-${m} דקות`
}

// ══════════════════════════════════════════════════════════════════════════════
//  GENERATORS
// ══════════════════════════════════════════════════════════════════════════════

function generateSites() {
  const sites = []
  for (let i = 0; i < N_SITES; i++) {
    const region = REGIONS[i % REGIONS.length]
    const war    = pick(WARS)
    const unit   = pick(UNITS)
    const [pfx, locType] = pick(SITE_TYPES)
    const noun   = pick(SITE_NOUNS)
    const lat = +(region[1] + rnd() * (region[2] - region[1])).toFixed(5)
    const lon = +(region[3] + rnd() * (region[4] - region[3])).toFixed(5)
    const gd  = randDateISO(war)
    const name = `${pfx}${pfx.endsWith('ל') ? '' : ' '}${noun} — ${region[0]}`
    const full = buildDescription(region, war, unit)
    sites.push({
      _region: region[0],
      name,
      city: region[0],
      latitude: lat, longitude: lon,
      category: war[1],
      location_type: locType,
      unit_name: unit,
      dedicated_to: buildDedication(unit, war),
      gregorian_date: gd,
      hebrew_date: '',
      description_snippet: full.split('. ')[0] + '.',
      full_description: full,
      cover_image_url: img(`nzmem-${i}-${region[0]}`, 1200, 800),
      wikidata_id: null,
    })
  }
  return sites
}

const ROUTE_TITLES = [
  'שביל הגבורה', 'בעקבות הלוחמים', 'מסע הזיכרון', 'דרך הנופלים',
  'נתיב הגיבורים', 'מסלול התקומה', 'שביל המגינים', 'בעקבות הצנחנים',
  'דרך הברית', 'מסע אל הנצח', 'שביל הדמעות והגאווה', 'נתיב המורשת',
]

// Length bands cycled across the routes so the dataset gets a healthy mix of
// short/medium/long trails instead of "everything > 8km".
const LENGTH_BANDS = [
  { key: 'short', maxKm: 3,  maxStops: 3 },
  { key: 'mid',   maxKm: 8,  maxStops: 4 },
  { key: 'long',  maxKm: 99, maxStops: 6 },
]

// Grow a route from a random seed by repeatedly appending the NEAREST unused
// site, stopping once the cumulative distance would cross the band ceiling
// (always keeps ≥2 stops so a route is never a single point). Bounding distance
// at *selection* time — not just ordering random picks — is what creates the
// short/mid/long variety.
function buildBoundedRoute(pool, band) {
  const remaining = [...pool]
  // Seed selection: the short/mid bands sample a few candidates and keep the
  // one with the closest neighbour, so the route can actually stay within the
  // band even in sparse regions. The long band just takes a random seed.
  let startIdx = Math.floor(rnd() * remaining.length)
  if (band.maxKm < 99) {
    let best = Infinity
    for (let t = 0; t < 5; t++) {
      const ci = Math.floor(rnd() * remaining.length)
      const cs = remaining[ci]
      let nn = Infinity
      remaining.forEach((s, idx) => {
        if (idx === ci) return
        const dd = haversineKm(cs.latitude, cs.longitude, s.latitude, s.longitude)
        if (dd < nn) nn = dd
      })
      if (nn < best) { best = nn; startIdx = ci }
    }
  }
  const ordered   = [remaining.splice(startIdx, 1)[0]]
  let dist = 0
  while (remaining.length && ordered.length < band.maxStops) {
    const last = ordered[ordered.length - 1]
    let bi = 0, bd = Infinity
    remaining.forEach((s, idx) => {
      const dd = haversineKm(last.latitude, last.longitude, s.latitude, s.longitude)
      if (dd < bd) { bd = dd; bi = idx }
    })
    if (ordered.length >= 2 && dist + bd > band.maxKm) break
    dist += bd
    ordered.push(remaining.splice(bi, 1)[0])
  }
  return { ordered, dist: Math.round(dist * 10) / 10 }
}

function generateRoutes(sitesByRegion) {
  const routes = []
  const regions = Object.keys(sitesByRegion).filter(r => sitesByRegion[r].length >= 4)
  for (let i = 0; i < N_ROUTES; i++) {
    const region = regions[i % regions.length]
    const pool   = sitesByRegion[region]
    const band   = LENGTH_BANDS[i % LENGTH_BANDS.length]
    const { ordered, dist } = buildBoundedRoute(pool, band)
    const diff = pick(REGIONS.find(r => r[0] === region) ? [REGIONS.find(r => r[0] === region)[6]] : ['בינוני'])
    routes.push({
      _sites: ordered,
      title: `${pick(ROUTE_TITLES)} — ${region}`,
      description_short: `מסלול הנצחה ב${region} הכולל ${ordered.length} תחנות זיכרון, לאורך ${dist} ק"מ של נופים ועדות. מסע מטלטל בעקבות גבורת לוחמי ישראל.`,
      difficulty: diff,
      category: pick(['מורשת יחידה', ordered[0].category]),
      start_location: region,
      is_featured: i < 6,
      distance_km: dist,
      duration: durationHe(dist, ordered.length),
      cover_image_url: img(`nzrt-${i}-${region}`, 1200, 800),
      map_image_url:  img(`nzmap-${i}-${region}`, 900, 600),
    })
  }
  return routes
}

const PROF_BIOS = [
  'מטייל בסופי שבוע, אוסף סיפורי גבורה','קצין שריון במילואים','אם שכולה, מנציחה את בנה',
  'מורה דרך מוסמך לאתרי מורשת','חובב היסטוריה צבאית','מדריכה בתנועת נוער',
  'גמלאי צה"ל, לוחם גולני לשעבר','צלמת נוף ואנדרטאות','סטודנט להיסטוריה של עם ישראל',
  'מתנדב בארגוני הנצחה','עשתה את שביל ישראל פעמיים','מנחה סדנאות זיכרון לנוער',
  'בן למשפחת לוחמים מדור תש"ח','אדריכלית נוף, חוקרת עיצוב הנצחה','עיתונאי מורשת',
  'מורה לאזרחות, מוביל מסעות','חוקרת תולדות ההתיישבות','איש חינוך, מלווה משלחות',
  'לוחם מילואים בצנחנים','חובבת טיולי מורשת עם המשפחה',
]
const PNAME_F = ['נועה','מיכל','שירה','תמר','הדס','ליאת','ענת','יערה','דנה','אורית','גלי','רותם','שני','אביגיל','מאיה','קרן','סיגל','רוני','נטע','עדי']

const POST_TPL = [
  ['experience','חזרנו מ{x} — אין מילים','עשינו היום את {x} עם כל המשפחה. עצרנו בכל תחנה, קראנו את שמות הנופלים בקול, והשתתקנו. צאו מוקדם בבוקר, קחו מים, ותנו ללב להיפתח.'],
  ['experience','{x} — כל ישראלי חייב','סיימנו את {x}. בכל אנדרטה סיפור, בכל סיפור עולם שלם. חזרנו הביתה שקטים אבל מלאים גאווה.'],
  ['tribute','לזכרם — אחרי {x}','עמדתי מול האנדרטה ב{x} וחשבתי על הצעירים שלא חזרו. דקה של דממה ארוכה. יהי זכרם ברוך.'],
  ['question','שאלה על {x} — נגישות','מתכננים את {x} עם סבא בכיסא גלגלים. אילו תחנות נגישות? נשמח לטיפים מהקהילה.'],
  ['question','מתי הכי כדאי ל{x}?','רוצים לעשות את {x} בלי חום כבד — בוקר מוקדם או שקיעה? ואיך החניה שם?'],
  ['photo','תיעוד מ{x}','כמה פריימים מ{x} של היום. האור על האבן בשקיעה — מצמרר. תודה למי שמתחזק את האתרים.'],
  ['tribute','{x} — מסע של דמעות וגאווה','לקחתי את שכבת י"א ל{x}. כל אחד הדליק נר ואמר משפט. רגע חינוכי שלא יישכח.'],
]
const COMMENTS = [
  'מרגש עד דמעות, תודה ששיתפת.','היינו שם בשבוע שעבר — מסכים עם כל מילה.','יישר כוח על החינוך לזיכרון.',
  'אפשר מסלול מדויק? נצא עם הקהילה.','הוספתי לשמורים שלי, תודה!','חוויה ערכית בלי מסכים, ממליץ.',
  'אנחנו עושים את זה כל שנה בערב יום הזיכרון.','נקודת חניה חשובה — תודה שהזכרת.','מצמרר. עם ישראל חי.',
  'כל הכבוד שעצרת לספר.','נצח ישראל לא ישקר.','שיהיה זכרם ברוך, ושנדע לספר הלאה.',
  'כמה זמן עם עצירות? שוקל לקחת קבוצה.','תודה שאתה עושה את זה. חשוב מאוד.','בדיוק תכננו לשם — עכשיו בטוח.',
]

// ── Resilient insert (auto-strips unknown cols, detects missing tables) ──────
const MISSING = Symbol('missing')
async function insertResilient(sb, table, rows, selectCols, opts = {}) {
  if (!rows.length) return { inserted: 0, data: [] }
  let work = rows
  for (let a = 0; a < 14; a++) {
    let q = opts.upsert ? sb.from(table).upsert(work, { onConflict: opts.onConflict })
                        : sb.from(table).insert(work)
    if (selectCols) q = q.select(selectCols)
    const { data, error } = await q
    if (!error) return { inserted: work.length, data: data ?? [] }
    const m = error.message || ''
    if (error.code === 'PGRST205' || /Could not find the table/i.test(m)) return { inserted: 0, status: MISSING }
    const cm = m.match(/Could not find the '([^']+)' column/i) || m.match(/column "([^"]+)" of relation/i)
    if (cm) { const bad = cm[1]; work = work.map(r => { const c = { ...r }; delete c[bad]; return c }); continue }
    return { inserted: 0, error: m }
  }
  return { inserted: 0, error: 'too many column-strip retries' }
}
async function batchInsert(sb, table, rows, selectCols, opts) {
  let inserted = 0, data = [], status
  for (let i = 0; i < rows.length; i += BATCH) {
    const r = await insertResilient(sb, table, rows.slice(i, i + BATCH), selectCols, opts)
    if (r.status === MISSING) { status = MISSING; break }
    if (r.error) return { inserted, data, error: r.error }
    inserted += r.inserted; if (r.data) data = data.concat(r.data)
    process.stdout.write('.')
  }
  process.stdout.write('\n')
  return { inserted, data, status }
}
async function clearTable(sb, t) {
  const { error } = await sb.from(t).delete().gte('created_at', '1970-01-01')
  return error ? error.message : null
}

// ══════════════════════════════════════════════════════════════════════════════

async function main() {
  if (!SUPABASE_URL || !SUPABASE_KEY) { console.error('❌ חסרים משתני סביבה'); process.exit(1) }
  const sb = createClient(SUPABASE_URL, SUPABASE_KEY)
  const report = {}
  console.log('\n══════════════════════════════════════════════════════')
  console.log('   🚀  Nekudat Tziyon — MASSIVE Full-App Seeder')
  console.log('══════════════════════════════════════════════════════\n')

  // ── Clean slate ───────────────────────────────────────────────────────────
  console.log('🧹 מנקה את כל הטבלאות...')
  const { error: rpcErr } = await sb.rpc('truncate_seed_tables')
  if (rpcErr) {
    console.log(`   ⚠️  RPC truncate_seed_tables לא זמין — מנקה ידנית`)
    for (const t of ['community_comments','community_posts','saved_routes','saved_memorials',
                     'route_waypoints','site_galleries','community_activities','routes','memorial_sites'])
      await clearTable(sb, t)
  } else console.log('   ✓ נוקה דרך RPC')
  console.log('')

  // ── 1. memorial_sites ─────────────────────────────────────────────────────
  console.log(`🏛️  מייצר ומכניס ${N_SITES} אתרי הנצחה...`)
  const sites = generateSites()
  const siteRes = await batchInsert(sb, 'memorial_sites',
    sites.map(({ _region, ...r }) => r), 'id, name')
  const siteIds = siteRes.data.map(s => s.id)
  // attach db ids back (order preserved by batched insert)
  sites.forEach((s, i) => { s._id = siteIds[i] })
  report.memorial_sites = `${siteRes.inserted}`
  console.log(`   ✅ ${siteRes.inserted} אתרים (כולם עם cover_image_url)\n`)

  // ── 2. routes ─────────────────────────────────────────────────────────────
  console.log(`🗺️  מייצר ומכניס ${N_ROUTES} מסלולים...`)
  const byRegion = {}
  sites.forEach(s => { (byRegion[s._region] ||= []).push(s) })
  const routes = generateRoutes(byRegion)
  const routeRes = await batchInsert(sb, 'routes',
    routes.map(({ _sites, ...r }) => r), 'id, title')
  const routeIds = routeRes.data.map(r => r.id)
  report.routes = `${routeRes.inserted}`
  console.log(`   ✅ ${routeRes.inserted} מסלולים (cover + map images)\n`)

  // ── 3. route_waypoints ────────────────────────────────────────────────────
  console.log('📍 מכניס עצירות מסלול...')
  const wps = []
  routes.forEach((rt, idx) => {
    const rid = routeIds[idx]; if (rid == null) return
    rt._sites.forEach((s, k) => wps.push({
      route_id: rid, stop_order: k + 1, name: s.name,
      description: s.description_snippet, image_url: s.cover_image_url,
    }))
  })
  const wpRes = await batchInsert(sb, 'route_waypoints', wps)
  report.route_waypoints = `${wpRes.inserted}`
  console.log(`   ✅ ${wpRes.inserted} עצירות\n`)

  // ── 4. site_galleries ─────────────────────────────────────────────────────
  console.log('🖼️  מכניס גלריות תמונות...')
  const gals = []
  sites.forEach((s, i) => {
    if (s._id == null) return
    const n = ri(3, 5)
    for (let k = 1; k <= n; k++) gals.push({ site_id: s._id, image_url: img(`nzgal-${i}-${k}`, 1000, 700) })
  })
  const galRes = await batchInsert(sb, 'site_galleries', gals)
  report.site_galleries = `${galRes.inserted}`
  console.log(`   ✅ ${galRes.inserted} תמונות גלריה\n`)

  // ── 5. profiles (Auth Admin API) ──────────────────────────────────────────
  console.log(`👤 יוצר ${N_PROFILES} משתמשי Auth + profiles...`)
  await clearTable(sb, 'profiles')
  const { data: ex } = await sb.auth.admin.listUsers({ page: 1, perPage: 1000 })
  for (const u of ex?.users ?? []) if (u.email?.startsWith('nz-seed-')) await sb.auth.admin.deleteUser(u.id)
  const created = []
  for (let i = 0; i < N_PROFILES; i++) {
    const fn = `${(i % 2 ? pick(PNAME_F) : pick(FNAMES))} ${pick(LNAMES)}`
    const { data, error } = await sb.auth.admin.createUser({
      email: `nz-seed-${i + 1}@example.com`, password: randomUUID(),
      email_confirm: true, user_metadata: { full_name: fn },
    })
    if (error) { if (i < 3) console.log(`   ⚠️ ${error.message}`); continue }
    const initials = fn.split(' ').map(w => w[0]).join('״')
    created.push({ id: data.user.id, full_name: fn, initials,
      avatar_color: `hsl(${ri(0,359)} 45% 45%)`, bio: pick(PROF_BIOS),
      avatar_url: avatar(`nz-user-${i}`) })
    if ((i + 1) % 10 === 0) process.stdout.write(`   ...${i + 1}\n`)
  }
  const profRes = await batchInsert(sb, 'profiles', created, 'id', { upsert: true, onConflict: 'id' })
  const pids = created.map(p => p.id)
  const haveP = pids.length > 0
  report.profiles = `${created.length} auth · ${profRes.inserted} rows`
  console.log(`   ✅ ${created.length} משתמשי Auth, ${profRes.inserted} שורות profiles\n`)

  // ── 6. community_activities ───────────────────────────────────────────────
  console.log(`📣 מכניס ${N_ACTIVITY} פעילויות קהילה...`)
  await clearTable(sb, 'community_activities')
  const acts = []
  for (let i = 0; i < N_ACTIVITY; i++) {
    const kind = pick(['candle','candle','visit','route','story'])
    const uid  = haveP ? pick(pids) : null
    if (kind === 'route') {
      acts.push({ action_type: 'route', site_id: null,
        target_name: pick(routes).title, user_id: uid, created_at: backdatedISO(14) })
    } else {
      const s = pick(sites)
      acts.push({ action_type: kind, site_id: s._id ?? null,
        target_name: kind === 'story' ? `סיפור הנצחה · ${s.name}` : s.name,
        user_id: uid, created_at: backdatedISO(kind === 'candle' ? 7 : 14) })
    }
  }
  const actRes = await batchInsert(sb, 'community_activities', acts)
  report.community_activities = `${actRes.inserted}`
  console.log(`   ✅ ${actRes.inserted} פעילויות\n`)

  // ── 7. community_posts ────────────────────────────────────────────────────
  console.log(`📝 מכניס ${N_POSTS} פוסטים...`)
  let postIds = []
  if (await clearTable(sb, 'community_posts') && true) { /* clear ignore */ }
  const posts = []
  for (let i = 0; i < N_POSTS; i++) {
    const [type, tt, bb] = POST_TPL[i % POST_TPL.length]
    const onR = rnd() < 0.6
    const subj = onR ? pick(routes) : pick(sites)
    const label = onR ? subj.title : subj.name
    posts.push({
      author_id: haveP ? pick(pids) : null,
      route_id: onR ? routeIds[routes.indexOf(subj)] ?? null : null,
      site_id:  onR ? null : subj._id ?? null,
      title: tt.replace('{x}', label), body: bb.replace(/\{x\}/g, label),
      post_type: type, like_count: ri(0, 240), created_at: backdatedISO(30),
    })
  }
  const postRes = await batchInsert(sb, 'community_posts', posts, 'id')
  if (postRes.status === MISSING) {
    report.community_posts = '⏭️ הטבלה לא קיימת (הרץ schema_full_app.sql)'
    console.log('   ⏭️  community_posts לא קיימת — דולג\n')
  } else {
    postIds = postRes.data.map(p => p.id)
    report.community_posts = `${postRes.inserted}`
    console.log(`   ✅ ${postRes.inserted} פוסטים\n`)
  }

  // ── 8. community_comments ─────────────────────────────────────────────────
  console.log('💬 מכניס תגובות...')
  if (!postIds.length) {
    report.community_comments = '⏭️ אין פוסטים'
    console.log('   ⏭️  דולג\n')
  } else {
    await clearTable(sb, 'community_comments')
    const cs = []
    for (const pid of postIds) {
      const n = ri(1, 4)
      for (let k = 0; k < n; k++) cs.push({
        post_id: pid, author_id: haveP ? pick(pids) : null,
        body: pick(COMMENTS), created_at: backdatedISO(26),
      })
    }
    const cRes = await batchInsert(sb, 'community_comments', cs)
    report.community_comments = `${cRes.inserted}`
    console.log(`   ✅ ${cRes.inserted} תגובות\n`)
  }

  // ── 9. saves ──────────────────────────────────────────────────────────────
  console.log('⭐ מכניס שמורים...')
  if (!haveP) { report.saved_routes = report.saved_memorials = '⏭️ אין profiles'; console.log('   ⏭️  דולג\n') }
  else {
    const mkUnique = (n, idsB) => {
      const set = new Set(), out = []
      let guard = n * 20
      while (out.length < n && guard-- > 0) {
        const u = pick(pids), b = pick(idsB)
        const key = `${u}:${b}`; if (set.has(key)) continue
        set.add(key); out.push({ user_id: u, _b: b })
      }
      return out
    }
    const sr = mkUnique(N_SAVED_RT, routeIds.filter(x => x != null))
      .map(x => ({ user_id: x.user_id, route_id: x._b, created_at: backdatedISO(40) }))
    const srC = await clearTable(sb, 'saved_routes')
    if (srC && /Could not find the table/i.test(srC)) {
      report.saved_routes = '⏭️ הטבלה לא קיימת (הרץ schema_full_app.sql)'
      console.log('   ⏭️  saved_routes לא קיימת — דולג')
    } else {
      const r = await batchInsert(sb, 'saved_routes', sr)
      report.saved_routes = r.status === MISSING ? '⏭️ הטבלה לא קיימת' : `${r.inserted}`
      console.log(`   ✅ saved_routes: ${r.inserted ?? 0}`)
    }
    const sm = mkUnique(N_SAVED_MEM, siteIds.filter(x => x != null))
      .map(x => ({ user_id: x.user_id, site_id: x._b, created_at: backdatedISO(40) }))
    const smC = await clearTable(sb, 'saved_memorials')
    if (smC && /Could not find the table/i.test(smC)) {
      report.saved_memorials = '⏭️ הטבלה לא קיימת (הרץ schema_full_app.sql)'
      console.log('   ⏭️  saved_memorials לא קיימת — דולג\n')
    } else {
      const r = await batchInsert(sb, 'saved_memorials', sm)
      report.saved_memorials = r.status === MISSING ? '⏭️ הטבלה לא קיימת' : `${r.inserted}`
      console.log(`   ✅ saved_memorials: ${r.inserted ?? 0}\n`)
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────────
  console.log('══════════════════════════════════════════════════════')
  console.log('   📊  סיכום זריעה מסיבית')
  console.log('══════════════════════════════════════════════════════')
  for (const [k, v] of Object.entries(report)) console.log(`   ${k.padEnd(22)} : ${v}`)
  console.log('══════════════════════════════════════════════════════\n')
}

main().catch(e => { console.error('\n❌ נכשל:', e.message, e.stack); process.exit(1) })
